# Jekyll Defaults
title: baadnewz
description: baadnewz's website.
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://baadie.github.io/"
github: https://github.com/baadie
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: Fun
  url: /fun/
- text: Hunting
  url: /hunting/
- text: Pentest
  url: /pentest/  
- text: Tags
  url: /tags/
